name: AsyncAPI Validate

on:
  workflow_dispatch:
  push:
    paths:
      - "asyncapi.yml"
    branches-ignore: [main]
  pull_request:
    paths:
      - "asyncapi.yml"

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      #"standard step" where repo needs to be checked-out first
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3

      #Using another action for AsyncAPI for validation
      - name: Validate âœ…
        uses: WaleedAshraf/asyncapi-github-action@v0.0.9
        with:
          filepath: asyncapi.yml
